name: Trigger Docker build

on:
  push:
    branches:
      - main

jobs:
  trigger:
    name: Trigger server Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DISPATCH_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'kowloon',
              workflow_id: 'docker.yml',
              ref: 'main',
            })
